module(load="ommail")
template (name="mailBody" type="string" string="From %hostname%\nTimestamp : %timereported%\nSource    : %programname%\nSeverity  : %rsyslogseverity-text%\nMessage   :%msg%")

template (name="mailSubject" type="string" string="%hostname% - Rsyslog alert for Program - %programname%")

# Send on severity 0 Emergency, 1 Alert and 2 Critical 
if $rsyslogseverity <= 2 then {
   action(type="ommail" server="127.0.0.1" port="25"
       mailfrom="rsyslog@localhost"        
       mailto="root@localhost"
       subject.template="mailSubject"
       body.enable="on" template="mailBody"
       action.execonlyonceeveryinterval="60") # Tests: set for 1 min
}
